"""add_bgm_id

Revision ID: e2ad2876ced4
Revises: f3f5d907ce9f
Create Date: 2026-03-09 11:03:27.761275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ad2876ced4'
down_revision: Union[str, Sequence[str], None] = 'f3f5d907ce9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('properties')]
    
    if 'bgm_id' not in columns:
        op.add_column('properties', sa.Column('bgm_id', sa.String(), nullable=True))
        op.create_index(op.f('ix_properties_bgm_id'), 'properties', ['bgm_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_bgm_id'), table_name='properties')
    op.drop_column('properties', 'bgm_id')
    # ### end Alembic commands ###
